export const RGB_EFFECT_ANALOG = 51
export const RGB_EFFECT_PER_KEY = 52
export const RGB_EFFECT_TRIGGER_STATE = 53

export const triggerStateEditors = [
  {
    index: 0,
    key: "idle",
    label: "Idle",
    description: "Released and inactive",
  },
  {
    index: 1,
    key: "release",
    label: "Release",
    description: "Moving upward after reset",
  },
  {
    index: 2,
    key: "press",
    label: "Press",
    description: "Pressed while moving downward",
  },
  {
    index: 3,
    key: "hold",
    label: "Hold",
    description: "Pressed without active trigger motion",
  },
] as const

export type TriggerPreviewState = (typeof triggerStateEditors)[number]["key"]

export const rgbEffectOptions = [
  { value: "0", label: "Off" },
  { value: "1", label: "Solid Color" },
  { value: "2", label: "Alphas Mods" },
  { value: "3", label: "Gradient Up Down" },
  { value: "4", label: "Gradient Left Right" },
  { value: "5", label: "Breathing" },
  { value: "6", label: "Band Saturation" },
  { value: "7", label: "Band Value" },
  { value: "8", label: "Band Pinwheel Saturation" },
  { value: "9", label: "Band Pinwheel Value" },
  { value: "10", label: "Band Spiral Saturation" },
  { value: "11", label: "Band Spiral Value" },
  { value: "12", label: "Cycle All" },
  { value: "13", label: "Cycle Left Right" },
  { value: "14", label: "Cycle Up Down" },
  { value: "15", label: "Cycle Out In" },
  { value: "16", label: "Cycle Out In Dual" },
  { value: "17", label: "Rainbow Moving Chevron" },
  { value: "18", label: "Cycle Pinwheel" },
  { value: "19", label: "Cycle Spiral" },
  { value: "20", label: "Dual Beacon" },
  { value: "21", label: "Rainbow Beacon" },
  { value: "22", label: "Rainbow Pinwheels" },
  { value: "23", label: "Flower Blooming" },
  { value: "24", label: "Raindrops" },
  { value: "25", label: "Jellybean Raindrops" },
  { value: "26", label: "Hue Breathing" },
  { value: "27", label: "Hue Pendulum" },
  { value: "28", label: "Hue Wave" },
  { value: "29", label: "Pixel Fractal" },
  { value: "30", label: "Pixel Flow" },
  { value: "31", label: "Pixel Rain" },
  { value: "32", label: "Typing Heatmap" },
  { value: "33", label: "Digital Rain" },
  { value: "34", label: "Solid Reactive Simple" },
  { value: "35", label: "Solid Reactive" },
  { value: "36", label: "Solid Reactive Wide" },
  { value: "37", label: "Solid Reactive Multi-Wide" },
  { value: "38", label: "Solid Reactive Cross" },
  { value: "39", label: "Solid Reactive Multi-Cross" },
  { value: "40", label: "Solid Reactive Nexus" },
  { value: "41", label: "Solid Reactive Multi-Nexus" },
  { value: "42", label: "Splash" },
  { value: "43", label: "Multi-Splash" },
  { value: "44", label: "Solid Splash" },
  { value: "45", label: "Solid Multi-Splash" },
  { value: "46", label: "Starlight" },
  { value: "47", label: "Starlight Smooth" },
  { value: "48", label: "Starlight Dual Hue" },
  { value: "49", label: "Starlight Dual Saturation" },
  { value: "50", label: "Riverflow" },
  { value: "51", label: "Analog Keypress" },
  { value: "52", label: "Per-Key / Static" },
  { value: "53", label: "Trigger State" },
] as const
